name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Ù‡Ø± ÙˆÙ‚Øª Ø¨Ù‡ Ø´Ø§Ø®Ù‡ main Ù¾ÙˆØ´ Ø´Ø¯ØŒ Ø§ÛŒÙ† Ø±Ø¨Ø§Øª ÙØ¹Ø§Ù„ Ù…ÛŒØ´Ù‡

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Ø±ÙˆÛŒ ÛŒÚ© Ø³Ø±ÙˆØ± Ù…Ø¬Ø§Ø²ÛŒ Ø§ÙˆØ¨ÙˆÙ†ØªÙˆ Ø§Ø¬Ø±Ø§ Ù…ÛŒØ´Ù‡

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3 # Ù‚Ø¯Ù… Ø§ÙˆÙ„: Ú©Ø¯ ØªÙˆ Ø±Ùˆ Ø§Ø² Ø±ÛŒÙ¾Ø§Ø²ÛŒØªÙˆØ±ÛŒ Ø¯Ø§Ù†Ù„ÙˆØ¯ Ù…ÛŒâ€ŒÚ©Ù†Ù‡

      - name: Install and Build ğŸ”§
        run: |
          npm install
          npm run build # Ù‚Ø¯Ù… Ø¯ÙˆÙ…: Ù¾Ø±ÙˆÚ˜Ù‡ Ø±Ùˆ Build Ù…ÛŒâ€ŒÚ©Ù†Ù‡ (Ù¾ÙˆØ´Ù‡ dist Ø³Ø§Ø®ØªÙ‡ Ù…ÛŒØ´Ù‡)

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Ù‚Ø¯Ù… Ø³ÙˆÙ…: Ù…Ø­ØªÙˆÛŒØ§Øª Ù¾ÙˆØ´Ù‡ dist Ø±Ùˆ Ø¨Ù‡ ÛŒÚ© Ø´Ø§Ø®Ù‡ Ø¬Ø¯ÛŒØ¯ Ø¨Ù‡ Ø§Ø³Ù… gh-pages Ù…Ù†ØªÙ‚Ù„ Ù…ÛŒâ€ŒÚ©Ù†Ù‡
          folder: dist # Ø§Ø² Ù¾ÙˆØ´Ù‡ dist